[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sqla-example"
version = "0.1"
description = "Example of relationship path error"
dependencies = ["sqlalchemy~=2.0.30"]
